spring.application.name=ms-mensajeria

# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
# Asignamos un puerto específico para evitar choques con los otros microservicios de tus compañeros
server.port=8083

# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# ==========================================
# URL de conexión. Crea la base de datos 'mensajeria_db' automáticamente si no existe
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
# ¡ATENCIÓN! Cambia "root" por la contraseña que usas para entrar a tu MySQL Workbench
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURACIÓN DE JPA E HIBERNATE
# ==========================================
# "update" hace que Spring cree o modifique tus tablas en MySQL automáticamente según tu Entidad
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la terminal (súper útil para ver qué está haciendo por detrás)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# CONFIGURACIÓN PARA SUBIDA DE ARCHIVOS (Multipart)
# ==========================================
# Límite de peso para un solo archivo adjunto (ej: 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB
# Límite de peso para la petición completa (por si mandan textos muy largos + el archivo)
spring.servlet.multipart.max-request-size=15MB

# ==========================================
# CONFIGURACIÓN DE SWAGGER / OPENAPI
# ==========================================
# Al correr el proyecto, entra a http://localhost:8084/swagger-ui.html para ver y probar tus endpoints
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

